Version check
nikkibisarya/CodeU-Summer-2017 pull request #1
Opened 2017-05-30 21:58 UTC by nikkibisarya

Here are my additions to ensure that version check works.

2017-05-31 04:15 UTC, willyjlee commented
LGTM

2017-05-31 06:08 UTC, adrnswanberg requested changes
Nice work! Mostly just nitpicks.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> -
nit: re-insert line break.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +
nit: remove line

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +
nit: remove these two lines.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/server/Server.java
> +
nit: remove blank line

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/client/core/View.java
> +        // Communicate this error - the server did not respond with the type of
Maybe you could write something to the console here to inform the user?

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/client/core/View.java
> +      // Communicate this error - something went wrong with the connection.
Same here.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +          // Communicate error to user - the server did not send us a valid
nit: Remove this comment.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +          // Print the server info to the user in a pretty way
This one too.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/common/ServerInfo.java
> +    {
nit: move open bracket to line above for consistency.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/common/ServerInfo.java
> +        {
nit: move open bracket to line above for consistency.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/common/ServerInfo.java
> +            //this.version = Uuid.NULL;
I'm not sure you just want to silently suppress this error. If the uuid can't be parsed, that's a serious enough error to let the program fail I think.

2017-05-31 06:08 UTC, adrnswanberg commented on src/codeu/chat/server/View.java
> +  public ServerInfo getInfo(){return null;}
nit: move `return null;` to next line.

2017-06-04 06:16 UTC, nikkibisarya commented on src/codeu/chat/common/ServerInfo.java
> +            //this.version = Uuid.NULL;
The code doesn't compile unless the exception is handled.

2017-06-04 20:17 UTC, adrnswanberg approved these changes
Looks good! Just address a few final comments before merging.

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/client/core/View.java
>          // Communicate this error - the server did not respond with the type of
nit: remove this comment

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/client/core/View.java
>        // Communicate this error - something went wrong with the connection.
nit: remove this comment

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/common/ServerInfo.java
> +            //this.version = Uuid.NULL;
I see. Then you could log an error and set this.version to Uuid.NULL.

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/common/ServerInfo.java
> +        catch(IOException e) {
nit: move the catch statement to the line above so that it looks like `} catch(...`

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/client/core/View.java
> +  @Override
nit: add blank line above

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/client/core/View.java
> +        // Communicate this error - the server did not respond with the type of
nit: remove comment

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/client/core/View.java
> +      // Communicate this error - something went wrong with the connection.
nit: remove comment

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/common/NetworkCode.java
> +
nit: remove blank line

2017-06-04 20:17 UTC, adrnswanberg commented on src/codeu/chat/common/ServerInfo.java
> +    public ServerInfo(Uuid version) {
nit: insert blank line above

2017-06-05 17:38 UTC, merged