Adding access restriction feature
nikkibisarya/CodeU-Summer-2017 pull request #12
Opened 2017-08-02 19:04 UTC by willyjlee

2017-08-03 05:44 UTC, adrnswanberg requested changes
Nice work! Nothing too major from me. Address my comments and you'll be good to merge. Let's push hard and try to get everything merged by Friday!

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/client/core/Controller.java
> +  // TODO: add return options, no user found, no access,
Implement this TODO or remove it if it does not necessary to complete this feature.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/client/core/Controller.java
> +
nit: remove blank line

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/client/core/Controller.java
> +
same here

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/client/core/ConversationContext.java
> +  public boolean changeAccess(Uuid requestor, String userName, String access, Uuid conversation) {
If access really only has three allowed values, you should probably make it an enum.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/AccessCode.java
> +public final class AccessCode {
This seems like a duplicate of Access.java? If so, remove and use Access.java everywhere.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/Access.java
> +public enum Access {
This doesn't conform to the google style guide: https://google.github.io/styleguide/javaguide.html#s4.8.1-enum-classes

I'm skeptical that you need the extra methods here too. I know java lets you do a lot with enum classes, but usually you just need a few definitions and that's it.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/ChangeAccessRequest.java
> +  public ChangeAccessRequest(Uuid user, Uuid conversation, Access access) {
nit: prefer to keep instance variables and constructor at the top of the class (in that order).

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/ChangeAccessRequest.java
> +
nit: remove blank line

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/ChangeAccessRequest.java
> +      // TODO: add reading convoid, access, convoid, access, ...
implement this todo or remove it if it is no longer necessary. also remove commented out code.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/ChangeAccessRequest.java
> +
nit: remove blank line

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/ConversationHeader.java
> +    // @Override
remove commented out code.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/User.java
> +  private Map<Uuid, Access> map;
give this a more descriptive name, and move it closer to the other instance variables.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/Writeable.java
> +  public static final String CHANGE_ACCESS_REQUEST_STR = "changeaccessrequest";
in retrospect, these could have probably been enum values. you don't necessarily have to change it though.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/User.java
> +  public void add(Uuid conversation, Access access) {
These methods should have more descriptive names.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/server/Controller.java
> +    if (requestorAccess!=Access.CREATOR && requestorAccess!=Access.OWNER) {
nit: add space between '!='

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/server/Controller.java
> +    if (access.equals(AccessCode.CREATOR)) {
This should be up higher before other checks.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/server/Controller.java
> +    // TODO: add persistent here
Implement TODO or remove if it is no longer necessary.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/server/Controller.java
> +
nit: remove blank line

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/server/Controller.java
> +
nit: remove blank line

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/server/Controller.java
> +    //getUser.add(conversation, Access.MEMBER);
remove commented out code, and blank line below.

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/server/Controller.java
> +
nit: remove blank line

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/server/Controller.java
> +
same here

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/util/Time.java
> +  // @Override
remove commented out code

2017-08-03 05:44 UTC, adrnswanberg commented on src/codeu/chat/common/AccessCode.java
> +public final class AccessCode {
Yeah, so after looking at the rest of the changes, you can definitely get rid of this and just use Access everywhere.

2017-08-04 04:54 UTC, adrnswanberg approved these changes
Nice, that's a wrap! You should all be proud of yourselves :)

2017-08-04 04:54 UTC, adrnswanberg commented on src/codeu/chat/common/AccessCode.java
> +// // Copyright 2017 Google Inc.
delete this file

2017-08-04 04:56 UTC, kaki123 commented on src/codeu/chat/common/ChangeAccessRequest.java
> +  public ChangeAccessRequest(Uuid user, Uuid conversation, Access access) {
This is resolved

2017-08-04 05:14 UTC, merged