tokenizing input: added class Tokenizer, tests, changed handleCommand…
nikkibisarya/CodeU-Summer-2017 pull request #2
Opened 2017-05-31 00:01 UTC by willyjlee

Added Tokenizer class, Tokenizer tests, handleCommand, and List instead of Scanner for commands

2017-05-31 00:52 UTC, nikkibisarya commented
LGTM

2017-05-31 20:40 UTC, adrnswanberg requested changes

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +import java.util.*;
Wildcard imports violates the Google java style guide. Please revert back to importing individual packages.

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +import java.lang.*;
Remove wildcard import.

2017-05-31 20:40 UTC, adrnswanberg commented on test/codeu/chat/util/TokenizerTest.java
> +import static org.junit.Assert.*;
Remove wildcard import.

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +public final class Tokenizer{
nit: add space before open bracket, here and everywhere else.

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    if(read()!='"'){
nit: add space between symbols, here and below

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +    for (String token = tokenizer.next(); token!=null; token = tokenizer.next()){
add spaces to this expression: `token!=null;`

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +        final String name = args.size()>0 ? args.get(0).trim() : ""; // this only takes first token of the name (surround with quotes for inputs with whitespaces)
nit: add symbols between spaces, and move comment to previous line.

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +        final String name = args.size()>0 ? args.get(0).trim() : ""; // this only takes first token of the name (surround with quotes for inputs with whitespaces)
same here.

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +        final String name = args.size()>0 ? args.get(0).trim() : ""; // this only takes first token of the conversation name (surround with quotes for inputs with whitespaces)
same here

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +        final String name = args.size()>0 ? args.get(0).trim() : ""; // this only takes first token of the conversation name (surround with quotes for inputs with whitespaces)
same here

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Chat.java
> +        final String message = args.size()>0 ? args.get(0).trim() : ""; // this only takes first token of the msg (surround with quotes for inputs with whitespaces)
same here

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Panel.java
> +import java.util.*;
remove wildcard import

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/client/commandline/Panel.java
> +    if(command != null){
re-insert spaces between symbols

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    else if(peek() == '"'){
nit: move `else if` to start on previous line

2017-05-31 20:40 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    else{
same here

2017-06-04 02:42 UTC, adrnswanberg approved these changes
Nice! Just address a few nits and you're free to merge.

2017-06-04 02:42 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    if(at < source.length()) {
nit: add space after `if`

2017-06-04 02:42 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    while(remaining() > 0 && !Character.isWhitespace(peek())){
nit: add space `while`

2017-06-04 02:42 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    if(read() != '"') {
nit: add space after if

2017-06-04 02:42 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    while(peek() != '"') {
nit: add space after while

2017-06-04 02:42 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    while(remaining() > 0 && Character.isWhitespace(peek())){
nit: add space after while

2017-06-04 02:42 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    if(remaining() <= 0) {
nit: add space after if

2017-06-04 02:42 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    } else if(peek() == '"'){
nit: add space after if

2017-06-04 02:42 UTC, adrnswanberg commented on src/codeu/chat/util/Tokenizer.java
> +    } else{
nit: add space after else

2017-06-06 18:23 UTC, merged